AS := sdas8051
CC := sdcc
CPP := sdcc -E
STCGAL := stcgal

OUT := build
MAIN := main

SOURCES_C = $(wildcard src/*.c)
SOURCES_S = $(wildcard src/*.s)
INCLUDES = include

STCFLAGS := -P stc15 --trim 5000 -o cpu_core_voltage=low -b 115200
CPPFLAGS := -DFOSC=2500000
CFLAGS := -mmcs51 --opt-code-size --no-xinit-opt --std-sdcc99 --funsigned-char --stack-auto
LDFLAGS := --out-fmt-ihx --iram-size 256 --xram-size 0 --code-size 8192

uniq = $(if $1,$(firstword $1) $(call uniq,$(filter-out $(firstword $1),$1)))
INCS := $(addprefix -I,$(INCLUDES))
OBJS := $(SOURCES_C:.c=.rel) $(SOURCES_S:.s=.rel)
OBJS := $(addprefix $(OUT)/,$(OBJS))
DEPS := $(OBJS:.rel=.d)
DIRS := $(call uniq,$(dir $(OBJS)))

ifneq ($(V),1)
Q := @
endif

.SUFFIXES:

.PHONY: all
all: $(OUT)/$(MAIN).ihx

.PHONY: clean
clean:
	@echo "  CLEAN"
	$(Q)rm -rf $(OUT)

-include $(DEPS)

$(OUT) $(DIRS):
	$(Q)mkdir -p $@

$(OBJS) $(DEPS): | $(DIRS) $(OUT)

$(OUT)/%.d: %.c
	@echo "  DEP $(notdir $@)"
	$(eval TMP := $(shell $(CPP) $(INCS) $(CPPFLAGS) -MMD $<))
	$(Q)echo "$(dir $@)$(TMP)" >$@

$(OUT)/%.rel: %.c
	@echo "  CC  $(notdir $@)"
	$(Q)$(CC) $(CFLAGS) $(INCS) $(CPPFLAGS) -c -o $@ $<

$(OUT)/%.rel: %.s
	@echo "  AS  $(notdir $@)"
	$(Q)$(AS) -c -o $@ $<

$(OUT)/$(MAIN).ihx: $(OBJS)
	@echo "  LD  $(notdir $@)"
	$(Q)$(CC) $(OBJS) -o $@ $(LIBS) $(CFLAGS) $(LDFLAGS) 

.PHONY: flash
flash: $(OUT)/$(MAIN).ihx
	$(Q)$(STCGAL) $(STCFLAGS) $<
